### PR TITLE
Picaweb fix

### PR DESCRIPTION
**Pull request by mugol**
Videobug changed it's player a little, so I made some small changes so at least the Picaweb sources work.

### CODE REVIEW

**Comment by CLFNole** [comment]
Was an update pushed?

**Comment by mugol** [comment]
Nah, azn needs to ok the change.

**Comment by CLFNole** [comment]
Cool thanks for the update!

**Comment by aznhusband** [comment]
Just started digging into this, saw you fixed it already. LOL.

I'll get a new version going.

**Pull request merged**
